FROM rust:1.89-slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    libpcsclite-dev \
    pcscd \
    pcsc-tools \
    libudev-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY .env ./

RUN cargo build --release

CMD ["/bin/bash"]
